### ISSUE TITLE
Work with Shiny Server

### ISSUE THREAD

**Issue by dylanrussellmd** [JohnCoene/firebase#18]
Hello,

I am trying to get this to work with an application hosted on Shiny Server. I host my application in the standard `/svr/shiny-server/` location under a subdirectory called `svr/shiny-server/prod`.

When I follow the basic authentication example (the one that just uses a very simple email and Google sign-in), I just get a blank page. However, I know something is working because in my Shiny logs, I see the warning message about terms of service. If it means anything, my `firebase.rds` file is located in the same directory as my `app.R` (that is, `/svr/shiny-server/prod/firebase.rds`).

I can not seem to figure out why I can't get the Firebase log in to show. Any ideas? Could it have anything to do with needing to specify the `auth_domain` argument for the `firebase_config` function?

**Comment by JohnCoene** [comment]
In the latest version you use [environment variables](https://firebase.john-coene.com/guide/config/) instead of the config file.
By default firebase will look for the config file in the root of the app but this can be changed `Firebase$new(config_path = "/path/to/firebase.rds")`.

However, this should not be the issue here: the launch of the app would error I think if it could not read that file.
Did you add the URL of the deployed app to your firebase console?

Could you check the browser console (<kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>I</kbd> then look in the "console" tab)
If you see errors could you share them here?

**Comment by dylanrussellmd** [comment]
Here is an error from the console:

```
Uncaught ReferenceError: firebaseui is not defined
    at e.<anonymous> (core.js:85)
    at e.value (shinyapp.ts:717)
    at e.<anonymous> (shinyapp.ts:811)
    at e.value (shinyapp.ts:717)
    at e.value (shinyapp.ts:700)
    at PromisedConnection.i.onmessage (shinyapp.ts:350)
    at MultiplexClientChannel._conn.onmessage (shiny-server-client.min.js:1)
    at BufferedResendConnection.MultiplexClient._conn.onmessage (shiny-server-client.min.js:1)
    at BufferedResendConnection._handleMessage (shiny-server-client.min.js:1)
    at RobustConnection._handleMessage (shiny-server-client.min.js:1)
```

**Comment by dylanrussellmd** [comment]
Just want to let you know I upgraded to the development version of your package and my problem was resolved. I have no idea why, but I changed nothing about my code. For whatever reason, the CRAN version does not work for me.

**Comment by JohnCoene** [comment]
Ok.

The dev version is a big update I'm not surprised it fixes many bugs.
