### ISSUE TITLE
capturing error when authenticating using email password method

### ISSUE THREAD

**Issue by j-lim-sigma** [JohnCoene/firebase#24]
Hi, thanks for this useful package.

is there a way to capture the error message if user enters incorrect email or password? Thank you for your help.

**Comment by JohnCoene** [comment]
I never really thought of doing this. I think that can be added. Let me take a quick look.

**Comment by JohnCoene** [comment]
You should be able to obtain this with the `get_signed_in` method, it returns a named list with a `success` variable; a boolean to indicate if the sign in was successful.

**Comment by aleksandereiken** [comment]
Very interested in this too!

**Comment by ncullen93** [comment]
circling back to this because I also had the same issue -- seems like everything was returning NULL regardless of the success or failure. But after some digging it seems that a Shiny input variable called `fireblaze_signed_up_user` gets updated directly after the login attempt and holds the right info. So this code works for me in my server, where `signin_account_email` is just an action button:

```R 
f <- firebase::FirebaseEmailPassword$new()

observeEvent(
    input$signin_account_email, {
        f$sign_in(input$email, input$password)
    }
)

observeEvent(
    input$fireblaze_signed_up_user, {
        if (!is.null(input$fireblaze_signed_up_user$response$code)) {
            print('failed login')
        } else {
            print('successful login')
        }
    }
)
```
