### ISSUE TITLE
Package ‘firebase’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by noamanemobidata** [JohnCoene/firebase#44]
Package ‘firebase’ was removed from the CRAN repository.

Archived on 2022-10-03 as check issues were not corrected despite reminders.

**Comment by JohnCoene** [comment]
Apologies, I know but I can no longer maintain my packages on CRAN, it is taking far too much of my time; time I no longer have.

**Comment by dcaud** [comment]
I know this is closed, but this seems like a pretty big issue to keep open. Can you reopen and ask for volunteers to keep this on CRAN and updated?

**Comment by dcaud** [comment]
Pasting what the maintainer wrote in a different thread:

"It is maintained, there just isn't much to do, it's almost feature complete and stable. It is not on CRAN because 1) it's a lot of work to keep CRAN happy 2) this package rarely, but sometimes requires urgent updates for security reasons and CRAN does not allow this." - https://github.com/JohnCoene/firebase/issues/50#issuecomment-1447737142

So maybe it isn't *imperative* to keep on CRAN, given these issues. Perhaps this library is viable longterm?!

**Comment by JohnCoene** [comment]
If someone is willing to help maintain this package you are more than welcome, feel free to send me a message john[at]opifex.org

I use this package in client's applications so I will do my best to keep it maintained and up to date.
Google should keep the API stable and it should not require too much work (I think).

**Comment by munoztd0** [comment]
Accepted back to CRAN !
