### ISSUE TITLE
Cannot download through remotes::install_github

### ISSUE THREAD

**Issue by Mush-A** [JohnCoene/firebase#50]
Hi, I know this project is no longer in CRAN since it is not maintained. 

But I am unable to download this from remotes::install_github as well

```
> remotes::install_github("JohnCoene/firebase")
Downloading GitHub repo JohnCoene/firebase@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/JohnCoene/firebase/tarball/HEAD' failed
```
I reproduced the error on my coworker's machine as well.

**Comment by JohnCoene** [comment]
I just tried to install it and it worked fine, this is not an issue with firebase as far as I can tell.

What's the output of a simple curl?

```bash
curl https://api.github.com/repos/JohnCoene/firebase
```

It is maintained, there just isn't much to do, it's almost feature complete and stable. It is not on CRAN because 1) it's a lot of work to keep CRAN happy 2) this package rarely, but sometimes requires urgent updates for security reasons and CRAN does not allow this.

**Comment by Mush-A** [comment]
Oh right, that makes sense. Thanks for responding.

And the curl does output a JSON object. I am puzzled as to why it does not download through the above method.
